### ISSUE TITLE
file permissions not set when 'fileMode' set in assembly descriptor

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#51]
i have the following in my assembly descriptor (it's just the relevant snippet)

```
<fileSet>
  <directory>${project.build.scriptSourceDirectory}</directory>
  <outputDirectory>/</outputDirectory>
  <filtered>true</filtered>
  <includes>
    <include>startup.sh</include>
   </includes>
   <fileMode>755</fileMode>
</fileSet>
```

when my container gets built, the startup script doesn't have the correct permissions. i'm not sure if this something that should work in the context of this plugin or not.

i also tried setting the permission directly on the local filesystem to see if they carry over but was unsuccessful there as well. right now i'm working around this by specifying `bash startup.sh` as the command but that somewhat less then idea.

is this a bug? if not, do you have any suggestions on how this could be handled? i want this contained within the data container that gets built rather then mucking w/ the image that will be running it (which in this case is the 'official' tomcat instance).

**Comment by jgangemi** [comment]
this was fixed in 0.11.0

**Comment by dcalmbach** [comment]
Hi, i'm using version 0.11.2 and it seems that this issue is not fixed. i explored the temporary tar from assembly plugin which takes care of filemode, the tar created by maven-docker-plugin does not.

**Comment by dcalmbach** [comment]
Perhaps its a windows issue since i'm building on a windows box

**Comment by rhuss** [comment]
Thanks for reporting, I'll try to have a look for this.

**Comment by jgangemi** [comment]
i'm thinking this is windows related b/c the above works for me on a mac and linux machines.

**Comment by jgangemi** [comment]
also, what is the value of `fileMode`? i just realized what i posted above it slightly incorrect and it should be `<fileMode>0755</fileMode>`

trying to google but not coming up w/ much - it's possible this is a bug in the assembly plugin as well.

**Comment by dcalmbach** [comment]
my assembly.xml was :<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
    <id>docker</id>
    <fileSets>
        <fileSet>
            <directory>${project.basedir}/src/main/docker/tagr</directory>
            <outputDirectory>/</outputDirectory>
            <includes>
                <include>**/*</include>
            </includes>
        </fileSet>
       <filemode>755</filemode>
    </fileSets>
</assembly>

It is not a bug of the assembly plugin since creating a tar with mvn assembly:single -Ddescriptor=src/main/docker/assembly.xml creates the right attributes. And its surely a windows issue, since building on linux/macos creates the correct images.

**Comment by efollea** [comment]
The problem is that the fat/ntfs or any other file system like this ones which does not support linux like rights.
The proposed solution (#139) is to use as intermediary a system that does not rely on underling File system but the linux rights (ie: a tgz archive.)
